version: '3.8'

services:
  noble-backend:
    build: .
    container_name: noble_backend
    restart: always
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - DB_PATH=/app/data/reservations.db

  noble-frontend:
    build: ../HookahPla—Åe Noble Site
    container_name: noble_frontend
    restart: always
    depends_on:
      - noble-backend
    volumes:
      # Mount config
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf
      # Mount certs
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
      
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
